# Generated by Django 3.1 on 2020-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='图标')),
                ('pid', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联上级ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '分类数据',
                'verbose_name_plural': '分类数据',
                'db_table': 'data_category',
                'ordering': ['cat_id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsListData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('old_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='原价')),
                ('new_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='现价')),
                ('recommend', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐理由')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='链接')),
                ('classify', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类')),
            ],
            options={
                'verbose_name': '物品列表数据',
                'verbose_name_plural': '物品列表数据',
                'db_table': 'data_goods_list',
                'ordering': ['classify'],
            },
        ),
        migrations.CreateModel(
            name='HomeRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐标题')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐图片')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐价格')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐链接')),
            ],
            options={
                'verbose_name': '首页推荐管理',
                'verbose_name_plural': '首页推荐管理',
                'db_table': 'data_home_recommend',
            },
        ),
        migrations.CreateModel(
            name='HomeSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类图标')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类标题')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '首页分类管理',
                'verbose_name_plural': '首页分类管理',
                'db_table': 'data_home_sort',
            },
        ),
        migrations.CreateModel(
            name='SwiperImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, max_length=255, null=True, verbose_name='轮播图图片')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='链接网址')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
                'db_table': 'data_home_swiper',
            },
        ),
    ]
