# Generated by Django 3.1 on 2020-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联ID')),
                ('pid', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联上级ID')),
                ('belong', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('old_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='原价')),
                ('new_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='现价')),
                ('recommend', models.CharField(blank=True, max_length=255, null=True, verbose_name='优惠活动')),
                ('discuss', models.CharField(blank=True, max_length=255, null=True, verbose_name='评论')),
                ('classify', models.CharField(blank=True, max_length=255, null=True, verbose_name='归属')),
            ],
            options={
                'verbose_name': '物品详情图片及介绍',
                'verbose_name_plural': '物品详情图片及介绍',
                'db_table': 'data_goods_detail_data',
                'ordering': ['classify', 'cat_id'],
            },
        ),
    ]
