# Generated by Django 3.1 on 2020-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdata', '0002_goodsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslistdata',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='页码'),
        ),
    ]
